sbatch job_PNEOA.sh
sbatch job_PNEOA1.sh
sbatch job_PNEOA2.sh
sbatch job_PNEOA3.sh
sbatch job_PNEOA4.sh
sbatch job_PNEOA5.sh
sbatch job_PNEOA6.sh
sbatch job_PNEOC.sh
sbatch job_PNEOC1.sh
sbatch job_PNEOC2.sh
sbatch job_PNEOC3.sh
sbatch job_PNEOC4.sh
sbatch job_PNEOC5.sh
sbatch job_PNEOC6.sh
sbatch job_PNEOE.sh
sbatch job_PNEOE1.sh
sbatch job_PNEOE2.sh
sbatch job_PNEOE3.sh
sbatch job_PNEOE4.sh
sbatch job_PNEOE5.sh
sbatch job_PNEOE6.sh
sbatch job_PNEON.sh
sbatch job_PNEON1.sh
sbatch job_PNEON2.sh
sbatch job_PNEON3.sh
sbatch job_PNEON4.sh
sbatch job_PNEON5.sh
sbatch job_PNEON6.sh
sbatch job_PNEOO.sh
sbatch job_PNEOO1.sh
sbatch job_PNEOO2.sh
sbatch job_PNEOO3.sh
sbatch job_PNEOO4.sh
sbatch job_PNEOO5.sh
sbatch job_PNEOO6.sh